# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='is_ibmer',
            field=models.BooleanField(default=False),
        ),
    ]
